---
title: "make_node_colors"
author: "Rachael M. Cox"
date: "4/25/2019"
output: html_document
---

```{r setup}
library(tidyverse)
library(RColorBrewer)
library(colorspace)

setwd("/stor/work/Marcotte/project/rmcox/archive/deBruijn_prot_seqs_deprecated/node_files/")
```

### ACTIN
```{r}
# specify unique node file, specify color gradient ---------------------------------------

node_df <- read_csv("actin_orthogroup_nodes_7mer_allproteins_uniques.csv")

num_edges = nrow(node_df)
highest_prot_count = max(node_df$ProteinCount, na.rm=TRUE)

## warm color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","deeppink4","firebrick1","indianred1","lightgrey")))

## cool color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","#482677FF","#238A8DFF","lightseagreen","lightgrey")))

## viridis color ramp
#colfunc <- colorRampPalette((c("#440154FF","#482677FF","#238A8DFF","#238A8DFF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white")))

## viridis color ramp
colfunc <- colorRampPalette((c("#482677FF","darkmagenta","darkmagenta","#238A8DFF","#238A8DFF","#73D055FF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white","white","white")))

## lightning color ramp
#colfunc <- colorRampPalette((c("blue2","light green", "white", "white")))

## plasma color ramp
#colfunc <- colorRampPalette(c("mediumblue","#72008D","#AB1488","#AB1488","#D24E71","#D24E71","#D24E71","#E8853A","#ECC000","#ECC000","#DAFF47","#DAFF47","white","white","white","white"))

## plasma 2
colfunc <- colorRampPalette(c("mediumblue","#72008D","#72008D","#AB1488","#D24E71","#D24E71","#238A8DFF","#73D055FF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white","white"))

## purple yellow color ramp
#colfunc <- colorRampPalette(c("#80146E","#9C7ACD","#84C1F4","#7CEAF3","#A5FBDD","#D7FACD","#F5F2D8"))


# color by edge protein count ---------------------------------------

palette <- colfunc(highest_prot_count)
swatchplot(palette)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>%
      rownames_to_column() %>%
      mutate(red = red/255) %>%
      mutate(green = green/255) %>%
      mutate(blue = blue/255) %>% 
      rename(ProteinCount = rowname) %>% 
      mutate(ProteinCount = as.numeric(ProteinCount))

color_protcount_table <- node_df %>%
  left_join(palette_LGL_format, by=c("ProteinCount"))

color_file_protcount <- color_protcount_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_tsv(color_file_protcount, "/stor/work/Marcotte/project/rmcox/archive/deBruijn_prot_seqs_deprecated/color_file_protcount_actin.txt", col_names=FALSE)
```


### ACTIN (EGGNOG)
```{r}
# specify unique node file, specify color gradient ---------------------------------------

node_df <- read_csv("actin_COGorthogroup_nodes_7mer_allproteins_uniques.csv")

num_edges = nrow(node_df)
highest_prot_count = max(node_df$ProteinCount, na.rm=TRUE)

## warm color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","deeppink4","firebrick1","indianred1","lightgrey")))

## cool color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","#482677FF","#238A8DFF","lightseagreen","lightgrey")))

## viridis color ramp
#colfunc <- colorRampPalette((c("#440154FF","#482677FF","#238A8DFF","#238A8DFF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white")))

## viridis color ramp
colfunc <- colorRampPalette((c("#482677FF","darkmagenta","darkmagenta","#238A8DFF","#238A8DFF","#73D055FF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white","white","white")))

## lightning color ramp
#colfunc <- colorRampPalette((c("blue2","light green", "white", "white")))

## plasma color ramp
#colfunc <- colorRampPalette(c("mediumblue","#72008D","#AB1488","#AB1488","#D24E71","#D24E71","#D24E71","#E8853A","#ECC000","#ECC000","#DAFF47","#DAFF47","white","white","white","white"))

## purple yellow color ramp
#colfunc <- colorRampPalette(c("#80146E","#9C7ACD","#84C1F4","#7CEAF3","#A5FBDD","#D7FACD","#F5F2D8"))


# color by edge protein count ---------------------------------------

palette <- colfunc(highest_prot_count)
swatchplot(palette)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>%
      rownames_to_column() %>%
      mutate(red = red/255) %>%
      mutate(green = green/255) %>%
      mutate(blue = blue/255) %>% 
      rename(ProteinCount = rowname) %>% 
      mutate(ProteinCount = as.numeric(ProteinCount))

color_protcount_table <- node_df %>%
  left_join(palette_LGL_format, by=c("ProteinCount"))

color_file_protcount <- color_protcount_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_tsv(color_file_protcount, "/stor/work/Marcotte/project/rmcox/archive/deBruijn_prot_seqs_deprecated/color_file_protcount_actin_COG.txt", col_names=FALSE)
```

### COLLAGEN
```{r}
# specify unique node file, specify color gradient ---------------------------------------

node_df <- read_csv("collagen_COGorthogroup_nodes_7mer_allproteins_uniques.csv")

num_edges = nrow(node_df)
highest_prot_count = max(node_df$ProteinCount, na.rm=TRUE)

## warm color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","deeppink4","firebrick1","indianred1","lightgrey")))

## cool color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","#482677FF","#238A8DFF","lightseagreen","lightgrey")))

## viridis color ramp
#colfunc <- colorRampPalette((c("#440154FF","#482677FF","#238A8DFF","#238A8DFF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white")))

## viridis color ramp
#colfunc <- colorRampPalette((c("#482677FF","darkmagenta","darkmagenta","#238A8DFF","#238A8DFF","#73D055FF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white","white","white")))

## lightning color ramp
#colfunc <- colorRampPalette((c("blue2","light green", "white", "white")))

## plasma color ramp
#colfunc <- colorRampPalette(c("mediumblue","#72008D","darkmagenta","#AB1488","#AB1488","#D24E71","#D24E71","#D24E71","#E8853A","#ECC000","#ECC000","#DAFF47","#DAFF47","white","white","white","white"))

## plasma 2
colfunc <- colorRampPalette(c("mediumblue","#72008D","darkmagenta","#AB1488","#D24E71","#D24E71","#238A8DFF","#73D055FF","#73D055FF","#FDE72500","#FDE72500","papayawhip","white","white"))


## purple yellow color ramp
#colfunc <- colorRampPalette(c("#80146E","#9C7ACD","#84C1F4","#7CEAF3","#A5FBDD","#D7FACD","#F5F2D8"))


# color by edge protein count ---------------------------------------

palette <- colfunc(highest_prot_count)
swatchplot(palette)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>%
      rownames_to_column() %>%
      mutate(red = red/255) %>%
      mutate(green = green/255) %>%
      mutate(blue = blue/255) %>% 
      rename(ProteinCount = rowname) %>% 
      mutate(ProteinCount = as.numeric(ProteinCount))

color_protcount_table <- node_df %>%
  left_join(palette_LGL_format, by=c("ProteinCount"))

color_file_protcount <- color_protcount_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_tsv(color_file_protcount, "/stor/work/Marcotte/project/rmcox/archive/deBruijn_prot_seqs_deprecated/color_file_protcount_collagen.txt", col_names=FALSE)

```


### MYOSIN
```{r}
# specify unique node file, specify color gradient ---------------------------------------

node_df <- read_csv("myosin_orthogroup_nodes_7mer_allproteins_uniques.csv")

num_edges = nrow(node_df)
highest_prot_count = max(node_df$ProteinCount, na.rm=TRUE)

## warm color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","deeppink4","firebrick1","indianred1","lightgrey")))

## cool color ramp
#colfunc <- colorRampPalette(rev(c("#440154FF","#482677FF","#238A8DFF","lightseagreen","lightgrey")))

## viridis color ramp
colfunc <- colorRampPalette((c("#440154FF","#482677FF","#238A8DFF","#73D055FF","#FDE72500","papayawhip")))

## lightning color ramp
colfunc <- colorRampPalette((c("blue2","light green", "white", "white")))

# color by edge protein count ---------------------------------------

palette <- colfunc(highest_prot_count)
swatchplot(palette)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>%
      rownames_to_column() %>%
      mutate(red = red/255) %>%
      mutate(green = green/255) %>%
      mutate(blue = blue/255) %>% 
      rename(ProteinCount = rowname) %>% 
      mutate(ProteinCount = as.numeric(ProteinCount))

color_protcount_table <- node_df %>%
  left_join(palette_LGL_format, by=c("ProteinCount"))

color_file_protcount <- color_protcount_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_tsv(color_file_protcount, "/stor/work/Marcotte/project/rmcox/archive/deBruijn_prot_seqs_deprecated/color_file_protcount_myosin.txt", col_names=FALSE)

```

```{r}

```

```{r}
# specify unique node file & alphabetize, specify color gradient ---------------------------------------

node_df <- read_csv("myosin_orthogroup_nodes_7mer_allproteins_uniques.csv")
  
node_lgl <- read_delim("../LGL_files/myosin_orthogroup_nodes_7mer_allproteins_lgl.ncol", " ", col_names=FALSE) %>% 
  rename(Node1 = X1) %>% 
  rename(Node2 = X2)

num_edges = nrow(node_df)
highest_prot_count = max(node_df$ProteinCount, na.rm=TRUE)

node_df_ordered <- node_df %>%
     mutate(alphNode1 = pmin(Node1, Node2), alphNode2 = pmax(Node1, Node2)) %>%
     mutate(Node1 = alphNode1, Node2 = alphNode2) %>% 
     select(-alphNode1, -alphNode2)

## warm color ramp (for presentation/white background)
#colfunc <- colorRampPalette(rev(c("#440154FF","deeppink4","firebrick1","indianred1","lightgrey")))

## cool color ramp
colfunc <- colorRampPalette(rev(c("#440154FF","#482677FF","#238A8DFF","lightseagreen","lightgrey")))

## viridis color ramp (for high res images/black background)
#colfunc <- colorRampPalette(c("#440154FF","#482677FF","#238A8DFF","#73D055FF","#FDE72500","papayawhip"))


# color by edge protein count ---------------------------------------

palette <- colfunc(highest_prot_count)
swatchplot(palette)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>%
      rownames_to_column() %>%
      mutate(red = red/255) %>%
      mutate(green = green/255) %>%
      mutate(blue = blue/255) %>% 
      rename(ProteinCount = rowname) %>% 
      mutate(ProteinCount = as.numeric(ProteinCount))

color_protcount_table <- node_df_ordered %>%
  left_join(palette_LGL_format, by=c("ProteinCount"))

lgl_protcount_colors <- node_lgl %>%
  left_join(color_protcount_table, by=c("Node1","Node2"))

color_file_protcount <- color_protcount_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_csv(color_file_protcount, "/stor/work/Marcotte/project/rmcox/deBruijn_protein_maps/color_file_protcount_myosin.txt")

```

```{r }

# color by position ---------------------------------------------

## work in progress
## need to figure out how to separate protein edges N-term to C-term

node_df2 <- read_csv("myosin_orthogroup_nodes_7mer_allproteins_uniques.csv") %>% 
  rownames_to_column()


palette <- colfunc(num_edges)

palette_LGL_format <- as_tibble(t(col2rgb(palette))) %>% rownames_to_column() %>%
  mutate(red = red/255) %>%
  mutate(green = green/255) %>%
  mutate(blue = blue/255)

color_position_table <- node_df2 %>% 
  left_join(palette_LGL_format, by=c("rowname"))

color_file_position_myosin <- color_position_table %>% 
  select(Node1, Node2, red, green, blue)
  
write_csv(color_file_position_myosin, "/stor/work/Marcotte/project/rmcox/deBruijn_protein_maps/color_file_position_myosin.txt")

```

